name: Continuous Integration

on: 
  pull_request:
    branches:
      - master
    paths: 
      - 'src/**'
  push: 
    branches:
      - master
    paths: 
      - 'src/**'
  workflow_dispatch:

jobs:
  commands:
    name: Test Commands
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4

    - name: Use Node.js "18.x"
      uses: actions/setup-node@v4
      with:
        node-version: "18.x"
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Deploy Dev Commands
      run: npm run deploy:dev

    # - run: node -r dotenv/config src/index.js
    #   env:
    #     BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
    #     DEV_GUILD_ID: ${{ secrets.DEV_GUILD_ID }}

    - name: Test Commands
      run: npm run test

    - name: Undeploy Dev Commands
      run: npm run undeploy:dev

  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run linter
        run: npm run lint

  version:
    name: Version Bump 
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions: 
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Bump version
        uses: 4Source/version-control-action@v1
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repository:  ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          dry_run: true


